version: '3'

services:
  eventstore:
    image: eventstore/eventstore:20.10.2-buster-slim
    ports:
      - "1113:1113"
      - "2113:2113"
    environment:
      - EVENTSTORE_CLUSTER_SIZE=1
      - EVENTSTORE_RUN_PROJECTIONS=All
      - EVENTSTORE_START_STANDARD_PROJECTIONS=true
      - EVENTSTORE_EXT_TCP_PORT=1113
      - EVENTSTORE_HTTP_PORT=2113
      - EVENTSTORE_INSECURE=true
      - EVENTSTORE_ENABLE_EXTERNAL_TCP=true
      - EVENTSTORE_ENABLE_ATOM_PUB_OVER_HTTP=true
      - EVENTSTORE_MEM_DB=true
    volumes:
      - eventstore-data:/var/lib/eventstore
      - eventstore-logs:/var/log/eventstore

  mysql:
    image: mysql:latest
    restart: always
    environment:
      MYSQL_DATABASE: 'golangsp'
      MYSQL_USER: 'golangsp'
      MYSQL_PASSWORD: 'golangsp'
      MYSQL_ROOT_PASSWORD: 'root'
    ports:
      - "3306:3306"
    command: --default-storage-engine=MEMORY

volumes:
  eventstore-data:
  eventstore-logs:
